eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8002
spring:
  application:
    name: service-front

#开启服务熔断机制
feign:
  hystrix:
    enabled: true

#控制接口版本
api:
  version: v1