eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8003
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-front:
      path: /api-front/**
      serviceId: service-front
